### ISSUE TITLE
Where to "clean up" code

### ISSUE THREAD

**Issue by UvuvDev** [iProgramMC/NanoShellOS#21]
Hey, I want to contribute to this but I don't feel 100% comfortable with making new features yet. Never made an OS before! Hence I'm wondering if you could point out some of the files where you feel code should be reorganized, and then I can rework it. thanks in advance.

**Comment by iProgramMC** [comment]
I believe running `ls -R` in the src directory will tell you what needs reorganization.

Jokes aside, whatever you want to reorganize :)
The interrupt handling code is in a pretty dire state so I'd suggest this, if you really want, but you say you've never made an OS before... I'd say some components are well organized like the window manager code though.

**Comment by UvuvDev** [comment]
Ill take a shot then, thanks.
