### ISSUE TITLE
Add networking functionality

### ISSUE THREAD

**Issue by cursedUs64-git** [iProgramMC/NanoShellOS#23]
I use arch Linux (btw) but i use it with a laptop. Alot of people (like me) use wifi instead of ethernet, and so adding wireless (and ethernet, if not existing) functionality is a huge helpful thing for laptop users. If you do accept this request, then please do add drivers from Linux or open/freebsd. Sorry if this is too much bloat but please do.

**Comment by iProgramMC** [comment]
?

NanoShell does not feature any kind of network support nor plans to.
