### ISSUE TITLE
Port gcc to NSOS

### ISSUE THREAD

**Issue by cursedUs64-git** [iProgramMC/NanoShellOS#24]
I have seen that some people managed to compile gcc with tcc (here is a issue, which has a wikipedia page, referencing it: https://lists.nongnu.org/archive/html/tinycc-devel/2017-05/msg00099. Would it be possible to build older build of gcc with tcc with some patches, so that porting apps would become easier for NSOS?

**Comment by iProgramMC** [comment]
That is not happening I'm afraid.

Join the discord server linked in the readme if you want to dump your ideas, please do not create issues on the repo for that.
