### ISSUE TITLE
BUG: Chess allows illegal pawn moves.

### ISSUE THREAD

**Issue by Tetrapak0** [iProgramMC/NanoShellOS#27]
https://github.com/iProgramMC/NanoShellOS/assets/112382253/5017df7d-6dbc-414a-b64f-c28d0450b627

Video explains everything.

**Comment by iProgramMC** [comment]
Wow, it even thinks it's en passant! I'll fix it.  I think there may be other cases where NanoShell Chess lets you make illegal moves, but I don't remember them.
