### ISSUE TITLE
Use own Images / Icons

### ISSUE THREAD

**Issue by SpookyTabz** [iProgramMC/NanoShellOS#7]
i was wondering how i can change the icons / images, when i look in the include/icons folder and select a file it says converted something how do i do that?

**Comment by iProgramMC** [comment]
The way I did it originally can be seen looking in the commit history; it uses a C# program to convert png icons to header files. I still use that method but haven't bothered porting it to linux to use libpng, here's [the original source code](https://github.com/iProgramMC/NanoShellOS/blob/f48546a27dc23fdde1143cfb5abb5c056faab794/tools_src/icontest/Program.cs) if you'd like to have a try at porting it.

**Comment by SpookyTabz** [comment]
ok thanks for the help
